version: '3.3'
services:

  redis:
    container_name: dash-mn-payment-queue
    image: redis:alpine
    ports:
      - "6379:6379"

    
  
  database:
    container_name: dash-mn-payment-db
    image: sameersbn/postgresql:10
    environment:
      - DB_NAME=dash_mns
      - PG_TRUST_LOCALNET=true
    ports:
      - "5432:5432"

  manager:
    container_name: api
    environment:
      - RPC_PORT=9998
    build:
      context: ./containers/mn_api
      dockerfile: Dockerfile
    ports:
      - 80:5000
    links:
      - dash_server

  dash_server:
    container_name: dash_server
    image: dashpay/dashd:latest
    restart: always
    user: "0"
    volumes:
      - $PWD/dash.conf:/dash/.dashcore/dash.conf:ro
      - $PWD/containers/dashd/data:/dash/.dashcore/

    command: /usr/local/bin/dashd -conf=/dash/.dashcore/dash.conf

volumes:
  data:
