version: '3.3'

services:
  manager:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000

  dash_server:
    container_name: dash_server
    image: jefethechefe/docker-dashd-nexus
    command: -server
    ports:
      - 9998:9998
    volumes:
      - ${PWD}/data:/home/dash/.dashcore
      - type: bind
        source: ./dash.conf
        target: /home/dash/.dashcore/dash.conf
      - type: bind
        source: ./bootstrap.dat.zip
        target: /home/dash/.dashcore/bootstrap.dat.zip
  
volumes:
  data:
